version: 2
updates:
  - package-ecosystem: gomod
    directory: /go_module
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(go)"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "deps(actions)"
