package main

// LevelDoc defines documentation for a specific attribute level
type LevelDoc struct {
	Name   string `json:"name"`
	Effect string `json:"effect"`
	FPCost int    `json:"fp_cost,omitempty"`
	Tip    string `json:"tip,omitempty"`
}

// AttributeDef defines a Movie Battles II attribute
type AttributeDef struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	MaxLevel    int    `json:"max_level"`
	Category    string `json:"category"` // "General", "Weapons", "Force", "Saber", "Class Specific", "Advanced"
	Description string `json:"description"`

	// Rich Documentation
	Overview string              `json:"overview,omitempty"`
	Levels   map[string]LevelDoc `json:"levels,omitempty"` // map[string] because JSON keys are strings
	Tips     []string            `json:"tips,omitempty"`
	Tags     []string            `json:"tags,omitempty"`
}

type ClassDef struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ClassFlagDef struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Overview    string `json:"overview,omitempty"`
}

type SaberStyleDef struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Overview    string `json:"overview,omitempty"`
}

type GlossaryDef struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Overview    string `json:"overview,omitempty"`
}

var MBIIClassFlags = []ClassFlagDef{
	{ID: "CFL_STRONGAGAINSTPHYSICAL", Name: "Strong vs Physical"},
	{ID: "CFL_STATVIEWER", Name: "Stat Viewer"},
	{ID: "CFL_HEAVYMELEE", Name: "Heavy Melee"},
	{ID: "CFL_REALTD", Name: "Real Thermal Detonator"},
	{ID: "CFL_HASQ3", Name: "Has Q3"},
	{ID: "CFL_FASTHACKING", Name: "Fast Hacking"},
	{ID: "CFL_NOPICKUPS", Name: "No Pickups"},
	{ID: "CFL_BPFREEJUMPS", Name: "BP Free Jumps"},
	{ID: "CFL_SEEING_STEALTH", Name: "See Stealth"},
	{ID: "CFL_AKIMBOPISTOL3", Name: "Akimbo Pistol 3"},
	{ID: "CFL_THERMALROCKETS", Name: "Thermal Rockets"},
	{ID: "CFL_INSTAGIB", Name: "Instagib"},
	{ID: "CFL_ACIDBLOOD", Name: "Acid Blood"},
	{ID: "CFL_DISMEMBERFRAGILE", Name: "Dismember Fragile"},
	{ID: "CFL_BLOODYMELEE", Name: "Bloody Melee"},
	{ID: "CFL_BUBBLESHIELD", Name: "Bubble Shield"},
	{ID: "CFL_NO_FUEL_USE", Name: "No Fuel Use"},
	{ID: "CFL_NO_JETPACK_OVERHEAT", Name: "No Jetpack Overheat"},
	{ID: "CFL_NO_JETPACK_COOLDOWN", Name: "No Jetpack Cooldown"},
	{ID: "CFL_DISRUPTOR_WALLS", Name: "Disruptor Walls"},
	{ID: "CFL_KILLTEAMONDEATH", Name: "Kill Team on Death"},
	{ID: "CFL_NOLOCATIONALDAMAGE", Name: "No Locational Damage"},
	{ID: "CFL_RUNFASTMELEE", Name: "Run Fast Melee"},
	{ID: "CFL_NODISMEMBER", Name: "No Dismember"},
}

var MBIISaberStyles = []SaberStyleDef{
	{ID: "SS_NONE", Name: "None"},
	{ID: "SS_FAST", Name: "Fast / Blue"},
	{ID: "SS_MEDIUM", Name: "Medium / Yellow"},
	{ID: "SS_STRONG", Name: "Strong / Red"},
	{ID: "SS_DESANN", Name: "Desann / Purple"},
	{ID: "SS_TAVION", Name: "Tavion / Cyan"},
	{ID: "SS_DUAL", Name: "Dual Sabers"},
	{ID: "SS_STAFF", Name: "Saber Staff"},
}

var MBIIClasses = []ClassDef{
	{ID: "MB_CLASS_SOLDIER", Name: "Soldier", Description: "Standard infantry unit."},
	{ID: "MB_CLASS_JEDI", Name: "Jedi", Description: "Force user with lightsaber."},
	{ID: "MB_CLASS_HERO", Name: "Hero", Description: "Dash Rendar / Han Solo type."},
	{ID: "MB_CLASS_SITH", Name: "Sith", Description: "Dark side force user."},
	{ID: "MB_CLASS_TROOPER", Name: "Trooper", Description: "Imperial stormtrooper."},
	{ID: "MB_CLASS_COMMANDER", Name: "Commander", Description: "Squad leader with rally."},
	{ID: "MB_CLASS_BOUNTY_HUNTER", Name: "Bounty Hunter", Description: "Gadget-heavy mercenary."},
	{ID: "MB_CLASS_SBD", Name: "SBD", Description: "Super Battle Droid."},
	{ID: "MB_CLASS_WOOKIE", Name: "Wookiee", Description: "High health brawler."},
	{ID: "MB_CLASS_DROIDEKA", Name: "Droideka", Description: "Destroyer droid with shield."},
	{ID: "MB_CLASS_CLONETROOPER", Name: "Clone Trooper", Description: "Republic soldier."},
	{ID: "MB_CLASS_MANDALORIAN", Name: "Mandalorian", Description: "Jetpack warrior."},
	{ID: "MB_CLASS_ARCTROOPER", Name: "ARC Trooper", Description: "Elite clone trooper."},
	{ID: "MB_CLASS_ELITETROOPER", Name: "Elite Trooper", Description: "Heavy weapons specialist."},
}

var MBIIAttributes = []AttributeDef{
	{ID: "MB_ATT_FP_HEAL", Name: "Force Heal", MaxLevel: 3, Category: "Force", Description: "Force Heal attribute."},
	{ID: "MB_ATT_FP_LEVITATION", Name: "Force Levitation", MaxLevel: 3, Category: "Force", Description: "Force Levitation attribute."},
	{ID: "MB_ATT_FP_SPEED", Name: "Force Speed", MaxLevel: 3, Category: "Force", Description: "Force Speed attribute."},
	{ID: "MB_ATT_FP_PUSH", Name: "Force Push", MaxLevel: 3, Category: "Force", Description: "Force Push attribute."},
	{ID: "MB_ATT_FP_PULL", Name: "Force Pull", MaxLevel: 3, Category: "Force", Description: "Force Pull attribute."},
	{ID: "MB_ATT_FP_TELEPATHY", Name: "Force Telepathy", MaxLevel: 3, Category: "Force", Description: "Force Telepathy attribute."},
	{ID: "MB_ATT_FP_GRIP", Name: "Force Grip", MaxLevel: 3, Category: "Force", Description: "Force Grip attribute."},
	{ID: "MB_ATT_FP_LIGHTNING", Name: "Force Lightning", MaxLevel: 3, Category: "Force", Description: "Force Lightning attribute."},
	{ID: "MB_ATT_FP_RAGE", Name: "Force Rage", MaxLevel: 3, Category: "Force", Description: "Force Rage attribute."},
	{ID: "MB_ATT_FP_PROTECT", Name: "Force Protect", MaxLevel: 3, Category: "Force", Description: "Force Protect attribute."},
	{ID: "MB_ATT_FP_ABSORB", Name: "Force Absorb", MaxLevel: 3, Category: "Force", Description: "Force Absorb attribute."},
	{ID: "MB_ATT_FP_TEAM_HEAL", Name: "Force Team Heal", MaxLevel: 3, Category: "Force", Description: "Force Team Heal attribute."},
	{ID: "MB_ATT_FP_TEAM_FORCE", Name: "Force Team Force", MaxLevel: 3, Category: "Force", Description: "Force Team Force attribute."},
	{ID: "MB_ATT_FP_DRAIN", Name: "Force Drain", MaxLevel: 3, Category: "Force", Description: "Force Drain attribute."},
	{ID: "MB_ATT_FP_SEE", Name: "Force See", MaxLevel: 3, Category: "Force", Description: "Force See attribute."},
	{ID: "MB_ATT_FP_SABER_OFFENSE", Name: "Force Saber Offense", MaxLevel: 3, Category: "Force", Description: "Force Saber Offense attribute."},
	{ID: "MB_ATT_FP_SABER_DEFENSE", Name: "Force Saber Defense", MaxLevel: 3, Category: "Force", Description: "Force Saber Defense attribute."},
	{ID: "MB_ATT_FP_SABERTHROW", Name: "Force Saberthrow", MaxLevel: 3, Category: "Force", Description: "Force Saberthrow attribute."},
	{ID: "MB_ATT_FP_BLIND", Name: "Force Blind", MaxLevel: 3, Category: "Force", Description: "Force Blind attribute."},
	{ID: "MB_ATT_FP_DESTRUCTION", Name: "Force Destruction", MaxLevel: 3, Category: "Force", Description: "Force Destruction attribute."},
	{ID: "MB_ATT_FP_PROJECTION", Name: "Force Projection", MaxLevel: 3, Category: "Force", Description: "Force Projection attribute."},
	{ID: "MB_ATT_FP_DEADLYSIGHT", Name: "Force Deadlysight", MaxLevel: 3, Category: "Force", Description: "Force Deadlysight attribute."},
	{ID: "MB_ATT_FP_STASIS", Name: "Force Stasis", MaxLevel: 3, Category: "Force", Description: "Force Stasis attribute."},
	{ID: "MB_ATT_FP_BATTLEMED", Name: "Force Battlemed", MaxLevel: 3, Category: "Force", Description: "Force Battlemed attribute."},
	{ID: "MB_ATT_PISTOL", Name: "Pistol", MaxLevel: 3, Category: "Weapons", Description: "Pistol attribute."},
	{ID: "MB_ATT_BLASTER", Name: "Blaster", MaxLevel: 3, Category: "Weapons", Description: "Blaster attribute."},
	{ID: "MB_ATT_DISRUPTOR", Name: "Disruptor", MaxLevel: 3, Category: "General", Description: "Disruptor attribute."},
	{ID: "MB_ATT_BOWCASTER", Name: "Bowcaster", MaxLevel: 3, Category: "General", Description: "Bowcaster attribute."},
	{ID: "MB_ATT_SWORD", Name: "Sword", MaxLevel: 3, Category: "General", Description: "Sword attribute."},
	{ID: "MB_ATT_DURABILITY", Name: "Durability", MaxLevel: 3, Category: "General", Description: "Durability attribute."},
	{ID: "MB_ATT_SENTRY", Name: "Sentry", MaxLevel: 3, Category: "General", Description: "Sentry attribute."},
	{ID: "MB_ATT_LASERCOVER", Name: "Lasercover", MaxLevel: 3, Category: "General", Description: "Lasercover attribute."},
	{ID: "MB_ATT_ACROBACY", Name: "Acrobacy", MaxLevel: 3, Category: "General", Description: "Acrobacy attribute."},
	{ID: "MB_ATT_DRONE", Name: "Drone", MaxLevel: 3, Category: "General", Description: "Drone attribute."},
	{ID: "MB_ATT_WPFLAMETHROWER", Name: "Wpflamethrower", MaxLevel: 3, Category: "General", Description: "Wpflamethrower attribute."},
	{ID: "MB_ATT_CLONERIFLE", Name: "Clonerifle", MaxLevel: 3, Category: "Weapons", Description: "Clonerifle attribute."},
	{ID: "MB_ATT_PROJECTILE_RIFLE", Name: "Projectile Rifle", MaxLevel: 3, Category: "Weapons", Description: "Projectile Rifle attribute."},
	{ID: "MB_ATT_A280", Name: "A280", MaxLevel: 3, Category: "General", Description: "A280 attribute."},
	{ID: "MB_ATT_THERMALS", Name: "Thermals", MaxLevel: 3, Category: "Weapons", Description: "Thermals attribute."},
	{ID: "MB_ATT_HEALTH", Name: "Health", MaxLevel: 3, Category: "General", Description: "Health attribute."},
	{ID: "MB_ATT_ARMOUR", Name: "Armour", MaxLevel: 3, Category: "General", Description: "Armour attribute."},
	{ID: "MB_ATT_AMMO", Name: "Ammo", MaxLevel: 3, Category: "General", Description: "Ammo attribute."},
	{ID: "MB_ATT_POWER", Name: "Power", MaxLevel: 3, Category: "General", Description: "Power attribute."},
	{ID: "MB_ATT_REGEN", Name: "Regen", MaxLevel: 3, Category: "General", Description: "Regen attribute."},
	{ID: "MB_ATT_AP_MULTIPLIER", Name: "Ap Multiplier", MaxLevel: 3, Category: "General", Description: "Ap Multiplier attribute."},
	{ID: "MB_ATT_BP_MULTIPLIER", Name: "Bp Multiplier", MaxLevel: 3, Category: "General", Description: "Bp Multiplier attribute."},
	{ID: "MB_ATT_CS_MULTIPLIER", Name: "Cs Multiplier", MaxLevel: 3, Category: "General", Description: "Cs Multiplier attribute."},
	{ID: "MB_ATT_AS_MULTIPLIER", Name: "As Multiplier", MaxLevel: 3, Category: "General", Description: "As Multiplier attribute."},
	{ID: "MB_ATT_FP_MULTIPLIER", Name: "Force Multiplier", MaxLevel: 3, Category: "Force", Description: "Force Multiplier attribute."},
	{ID: "MB_ATT_ROF_MULTIPLIER", Name: "Rof Multiplier", MaxLevel: 3, Category: "General", Description: "Rof Multiplier attribute."},
	{ID: "MB_ATT_STM_MULTIPLIER", Name: "Stm Multiplier", MaxLevel: 3, Category: "General", Description: "Stm Multiplier attribute."},
	{ID: "MB_ATT_HACK_MULTIPLIER", Name: "Hack Multiplier", MaxLevel: 3, Category: "General", Description: "Hack Multiplier attribute."},
	{ID: "MB_ATT_KB_TAKEN_MULTIPLIER", Name: "Kb Taken Multiplier", MaxLevel: 3, Category: "General", Description: "Kb Taken Multiplier attribute."},
	{ID: "MB_ATT_KB_GIVEN_MULTIPLIER", Name: "Kb Given Multiplier", MaxLevel: 3, Category: "General", Description: "Kb Given Multiplier attribute."},
	{ID: "MB_ATT_DMG_TAKEN_MULTIPLIER", Name: "Dmg Taken Multiplier", MaxLevel: 3, Category: "General", Description: "Dmg Taken Multiplier attribute."},
	{ID: "MB_ATT_DMG_GIVEN_MULTIPLIER", Name: "Dmg Given Multiplier", MaxLevel: 3, Category: "General", Description: "Dmg Given Multiplier attribute."},
	{ID: "MB_ATT_BASESPEED", Name: "Basespeed", MaxLevel: 3, Category: "General", Description: "Basespeed attribute."},
	{ID: "MB_ATT_SABER_DAMAGE", Name: "Saber Damage", MaxLevel: 3, Category: "Saber", Description: "Saber Damage attribute."},
	{ID: "MB_ATT_SABERTHROW_DAMAGE", Name: "Saberthrow Damage", MaxLevel: 3, Category: "Saber", Description: "Saberthrow Damage attribute."},
	{ID: "MB_ATT_SABERSPECIAL_DAMAGE", Name: "Saberspecial Damage", MaxLevel: 3, Category: "Saber", Description: "Saberspecial Damage attribute."},
	{ID: "MB_ATT_MODELSCALE_MULTIPLIER", Name: "Modelscale Multiplier", MaxLevel: 3, Category: "General", Description: "Modelscale Multiplier attribute."},
	{ID: "MB_ATT_ROF_MELEE_MULTIPLIER", Name: "Rof Melee Multiplier", MaxLevel: 3, Category: "General", Description: "Rof Melee Multiplier attribute."},
	{ID: "MB_ATT_HEALTH_REGEN_CAP", Name: "Health Regen Cap", MaxLevel: 3, Category: "General", Description: "Health Regen Cap attribute."},
	{ID: "MB_ATT_HEALTH_REGEN_AMOUNT", Name: "Health Regen Amount", MaxLevel: 3, Category: "General", Description: "Health Regen Amount attribute."},
	{ID: "MB_ATT_HEALTH_REGEN_RATE", Name: "Health Regen Rate", MaxLevel: 3, Category: "General", Description: "Health Regen Rate attribute."},
	{ID: "MB_ATT_ARMOUR_REGEN_CAP", Name: "Armour Regen Cap", MaxLevel: 3, Category: "General", Description: "Armour Regen Cap attribute."},
	{ID: "MB_ATT_ARMOUR_REGEN_AMOUNT", Name: "Armour Regen Amount", MaxLevel: 3, Category: "General", Description: "Armour Regen Amount attribute."},
	{ID: "MB_ATT_ARMOUR_REGEN_RATE", Name: "Armour Regen Rate", MaxLevel: 3, Category: "General", Description: "Armour Regen Rate attribute."},
	{ID: "MB_ATT_RESOURCE_REGEN_CAP", Name: "Resource Regen Cap", MaxLevel: 3, Category: "General", Description: "Resource Regen Cap attribute."},
	{ID: "MB_ATT_RESOURCE_REGEN_AMOUNT", Name: "Resource Regen Amount", MaxLevel: 3, Category: "General", Description: "Resource Regen Amount attribute."},
	{ID: "MB_ATT_RESOURCE_REGEN_RATE", Name: "Resource Regen Rate", MaxLevel: 3, Category: "General", Description: "Resource Regen Rate attribute."},
	{ID: "MB_ATT_BLOCK_REGEN_CAP", Name: "Block Regen Cap", MaxLevel: 3, Category: "General", Description: "Block Regen Cap attribute."},
	{ID: "MB_ATT_BLOCK_REGEN_AMOUNT", Name: "Block Regen Amount", MaxLevel: 3, Category: "General", Description: "Block Regen Amount attribute."},
	{ID: "MB_ATT_BLOCK_REGEN_RATE", Name: "Block Regen Rate", MaxLevel: 3, Category: "General", Description: "Block Regen Rate attribute."},
	{ID: "MB_ATT_RESPAWNS", Name: "Respawns", MaxLevel: 3, Category: "General", Description: "Respawns attribute."},
	{ID: "MB_ATT_DODGE", Name: "Dodge", MaxLevel: 3, Category: "General", Description: "Dodge attribute."},
	{ID: "MB_ATT_HEALING", Name: "Healing", MaxLevel: 3, Category: "General", Description: "Healing attribute."},
	{ID: "MB_ATT_FLAMETHROWER", Name: "Flamethrower", MaxLevel: 3, Category: "General", Description: "Flamethrower attribute."},
	{ID: "MB_ATT_FUEL", Name: "Fuel", MaxLevel: 3, Category: "General", Description: "Fuel attribute."},
	{ID: "MB_ATT_FUELREGEN", Name: "Fuelregen", MaxLevel: 3, Category: "General", Description: "Fuelregen attribute."},
	{ID: "MB_ATT_ROCKET", Name: "Rocket", MaxLevel: 3, Category: "Weapons", Description: "Rocket attribute."},
	{ID: "MB_ATT_WOOKIE_HEALTH", Name: "Wookie Health", MaxLevel: 3, Category: "Class Specific", Description: "Wookie Health attribute."},
	{ID: "MB_ATT_WOOKIE_STRENGTH", Name: "Wookie Strength", MaxLevel: 3, Category: "Class Specific", Description: "Wookie Strength attribute."},
	{ID: "MB_ATT_HULL_STRENGTH", Name: "Hull Strength", MaxLevel: 3, Category: "General", Description: "Hull Strength attribute."},
	{ID: "MB_ATT_SHIELD_PROJ", Name: "Shield Proj", MaxLevel: 3, Category: "General", Description: "Shield Proj attribute."},
	{ID: "MB_ATT_DEKA_SHIELD", Name: "Deka Shield", MaxLevel: 3, Category: "Class Specific", Description: "Deka Shield attribute."},
	{ID: "MB_ATT_DEKA_HULL", Name: "Deka Hull", MaxLevel: 3, Category: "Class Specific", Description: "Deka Hull attribute."},
	{ID: "MB_ATT_DEKA_DEPLOY", Name: "Deka Deploy", MaxLevel: 3, Category: "Class Specific", Description: "Deka Deploy attribute."},
	{ID: "MB_ATT_DEKA_POWER", Name: "Deka Power", MaxLevel: 3, Category: "Class Specific", Description: "Deka Power attribute."},
	{ID: "MB_ATT_TURN_RATE", Name: "Turn Rate", MaxLevel: 3, Category: "General", Description: "Turn Rate attribute."},
	{ID: "MB_ATT_FIREPOWER", Name: "Firepower", MaxLevel: 3, Category: "General", Description: "Firepower attribute."},
	{ID: "MB_ATT_FIRERATE", Name: "Firerate", MaxLevel: 3, Category: "General", Description: "Firerate attribute."},
	{ID: "MB_ATT_QUICKTHROW", Name: "Quickthrow", MaxLevel: 3, Category: "General", Description: "Quickthrow attribute."},
	{ID: "MB_ATT_RECHARGE", Name: "Recharge", MaxLevel: 3, Category: "General", Description: "Recharge attribute."},
	{ID: "MB_ATT_STAMINA", Name: "Stamina", MaxLevel: 3, Category: "General", Description: "Stamina attribute."},
	{ID: "MB_ATT_DEXTERITY", Name: "Dexterity", MaxLevel: 3, Category: "General", Description: "Dexterity attribute."},
	{ID: "MB_ATT_KNOCKDOWN_ROLL", Name: "Knockdown Roll", MaxLevel: 3, Category: "General", Description: "Knockdown Roll attribute."},
	{ID: "MB_ATT_PULSE_GRENADES", Name: "Pulse Grenades", MaxLevel: 3, Category: "Weapons", Description: "Pulse Grenades attribute."},
	{ID: "MB_ATT_TRACKING_DART", Name: "Tracking Dart", MaxLevel: 3, Category: "General", Description: "Tracking Dart attribute."},
	{ID: "MB_ATT_POISON_DART", Name: "Poison Dart", MaxLevel: 3, Category: "General", Description: "Poison Dart attribute."},
	{ID: "MB_ATT_JETPACK", Name: "Jetpack", MaxLevel: 3, Category: "General", Description: "Jetpack attribute."},
	{ID: "MB_ATT_PLX1", Name: "Plx1", MaxLevel: 3, Category: "General", Description: "Plx1 attribute."},
	{ID: "MB_ATT_T21", Name: "T21", MaxLevel: 3, Category: "General", Description: "T21 attribute."},
	{ID: "MB_ATT_CLONEBLOBS", Name: "Cloneblobs", MaxLevel: 3, Category: "Class Specific", Description: "Cloneblobs attribute."},
	{ID: "MB_ATT_CORTOSIS", Name: "Cortosis", MaxLevel: 3, Category: "General", Description: "Cortosis attribute."},
	{ID: "MB_ATT_BLAST_ARMOUR", Name: "Blast Armour", MaxLevel: 3, Category: "General", Description: "Blast Armour attribute."},
	{ID: "MB_ATT_MAGNETIC_PLATING", Name: "Magnetic Plating", MaxLevel: 3, Category: "General", Description: "Magnetic Plating attribute."},
	{ID: "MB_ATT_WOOKIE_BALANCE", Name: "Wookie Balance", MaxLevel: 3, Category: "Class Specific", Description: "Wookie Balance attribute."},
	{ID: "MB_ATT_CCTRAINING", Name: "Cctraining", MaxLevel: 3, Category: "General", Description: "Cctraining attribute."},
	{ID: "MB_ATT_ET_CCTRAINING", Name: "Et Cctraining", MaxLevel: 3, Category: "General", Description: "Et Cctraining attribute."},
	{ID: "MB_ATT_MD_CCTRAINING", Name: "Md Cctraining", MaxLevel: 3, Category: "General", Description: "Md Cctraining attribute."},
	{ID: "MB_ATT_SBD_CANNON", Name: "Sbd Cannon", MaxLevel: 3, Category: "Class Specific", Description: "Sbd Cannon attribute."},
	{ID: "MB_ATT_WRISTLASER", Name: "Wristlaser", MaxLevel: 3, Category: "General", Description: "Wristlaser attribute."},
	{ID: "MB_ATT_SHOCKWAVE", Name: "Shockwave", MaxLevel: 3, Category: "General", Description: "Shockwave attribute."},
	{ID: "MB_ATT_SHIELD_RECHARGE", Name: "Shield Recharge", MaxLevel: 3, Category: "General", Description: "Shield Recharge attribute."},
	{ID: "MB_ATT_SHIELD_RECHARGE2", Name: "Shield Recharge2", MaxLevel: 3, Category: "General", Description: "Shield Recharge2 attribute."},
	{ID: "MB_ATT_RALLY", Name: "Rally", MaxLevel: 3, Category: "General", Description: "Rally attribute."},
	{ID: "MB_ATT_ASSEMBLE", Name: "Assemble", MaxLevel: 3, Category: "General", Description: "Assemble attribute."},
	{ID: "MB_ATT_SPY_DISGUISE", Name: "Spy Disguise", MaxLevel: 3, Category: "Class Specific", Description: "Spy Disguise attribute."},
	{ID: "MB_ATT_ARC_RIFLE_SCOPE", Name: "Arc Rifle Scope", MaxLevel: 3, Category: "Weapons", Description: "Arc Rifle Scope attribute."},
	{ID: "MB_ATT_ARC_RIFLE_GRENADELAUNCHER", Name: "Arc Rifle Grenadelauncher", MaxLevel: 3, Category: "Weapons", Description: "Arc Rifle Grenadelauncher attribute."},
	{ID: "MB_ATT_WOOKIEE_FURY", Name: "Wookiee Fury", MaxLevel: 3, Category: "Class Specific", Description: "Wookiee Fury attribute."},
	{ID: "MB_ATT_WOOKIEE_AGILITY", Name: "Wookiee Agility", MaxLevel: 3, Category: "Class Specific", Description: "Wookiee Agility attribute."},
	{ID: "MB_ATT_ANTI_MT", Name: "Anti Mt", MaxLevel: 3, Category: "General", Description: "Anti Mt attribute."},
	{ID: "MB_ATT_ZOOM", Name: "Zoom", MaxLevel: 3, Category: "General", Description: "Zoom attribute."},
	{ID: "MB_ATT_RADAR", Name: "Radar", MaxLevel: 3, Category: "General", Description: "Radar attribute."},
	{ID: "MB_ATT_GRAPPLE_HOOK", Name: "Grapple Hook", MaxLevel: 3, Category: "General", Description: "Grapple Hook attribute."},
	{ID: "MB_ATT_FIBERCORD_WHIP", Name: "Fibercord Whip", MaxLevel: 3, Category: "General", Description: "Fibercord Whip attribute."},
	{ID: "MB_ATT_FIRE_GRENADES", Name: "Fire Grenades", MaxLevel: 3, Category: "Weapons", Description: "Fire Grenades attribute."},
	{ID: "MB_ATT_CRYOBAN_GRENADES", Name: "Cryoban Grenades", MaxLevel: 3, Category: "Weapons", Description: "Cryoban Grenades attribute."},
	{ID: "MB_ATT_SONIC_DETONATOR", Name: "Sonic Detonator", MaxLevel: 3, Category: "General", Description: "Sonic Detonator attribute."},
	{ID: "MB_ATT_QUICKDRAW", Name: "Quickdraw", MaxLevel: 3, Category: "General", Description: "Quickdraw attribute."},
	{ID: "MB_ATT_MICRO_GRENADES", Name: "Micro Grenades", MaxLevel: 3, Category: "Weapons", Description: "Micro Grenades attribute."},
	{ID: "MB_ATT_IMPACT_NADE", Name: "Impact Nade", MaxLevel: 3, Category: "Weapons", Description: "Impact Nade attribute."},
	{ID: "MB_ATT_BACTA_BOMB", Name: "Bacta Bomb", MaxLevel: 3, Category: "General", Description: "Bacta Bomb attribute."},
	{ID: "MB_ATT_GAS_NADE", Name: "Gas Nade", MaxLevel: 3, Category: "Weapons", Description: "Gas Nade attribute."},
	{ID: "MB_ATT_FLASH_NADE", Name: "Flash Nade", MaxLevel: 3, Category: "Weapons", Description: "Flash Nade attribute."},
	{ID: "MB_ATT_GLOP_NADE", Name: "Glop Nade", MaxLevel: 3, Category: "Weapons", Description: "Glop Nade attribute."},
	{ID: "MB_ATT_IMPLODER_NADE", Name: "Imploder Nade", MaxLevel: 3, Category: "Weapons", Description: "Imploder Nade attribute."},
	{ID: "MB_ATT_SMOKE_NADE", Name: "Smoke Nade", MaxLevel: 3, Category: "Weapons", Description: "Smoke Nade attribute."},
	{ID: "MB_ATT_SHIELD_NADE", Name: "Shield Nade", MaxLevel: 3, Category: "Weapons", Description: "Shield Nade attribute."},
	{ID: "MB_ATT_PROTON_NADE", Name: "Proton Nade", MaxLevel: 3, Category: "Weapons", Description: "Proton Nade attribute."},
	{ID: "MB_ATT_STRONGBLOBS", Name: "Strongblobs", MaxLevel: 3, Category: "General", Description: "Strongblobs attribute."},
	{ID: "MB_ATT_STEALTH", Name: "Stealth", MaxLevel: 3, Category: "General", Description: "Stealth attribute."},
	{ID: "MB_ATT_BACKSTAB", Name: "Backstab", MaxLevel: 3, Category: "General", Description: "Backstab attribute."},
	{ID: "MB_ATT_DASH", Name: "Dash", MaxLevel: 3, Category: "General", Description: "Dash attribute."},
	{ID: "MB_ATT_DASH_JUMP", Name: "Dash Jump", MaxLevel: 3, Category: "General", Description: "Dash Jump attribute."},
	{ID: "MB_ATT_VIEWBASEDDRAIN", Name: "Viewbaseddrain", MaxLevel: 3, Category: "General", Description: "Viewbaseddrain attribute."},
	{ID: "MB_ATT_CLONE_PISTOL", Name: "Clone Pistol", MaxLevel: 3, Category: "Weapons", Description: "Clone Pistol attribute."},
	{ID: "MB_ATT_MANDO_PISTOL", Name: "Mando Pistol", MaxLevel: 3, Category: "Weapons", Description: "Mando Pistol attribute."},
	{ID: "MB_ATT_SPY_PISTOL", Name: "Spy Pistol", MaxLevel: 3, Category: "Weapons", Description: "Spy Pistol attribute."},
	{ID: "MB_ATT_IMP_PISTOL", Name: "Imp Pistol", MaxLevel: 3, Category: "Weapons", Description: "Imp Pistol attribute."},
	{ID: "MB_ATT_KNIFE", Name: "Knife", MaxLevel: 3, Category: "General", Description: "Knife attribute."},
	{ID: "MB_ATT_ELECTRO_STAFF", Name: "Electro Staff", MaxLevel: 3, Category: "General", Description: "Electro Staff attribute."},
	{ID: "MB_ATT_SHOTGUN", Name: "Shotgun", MaxLevel: 3, Category: "General", Description: "Shotgun attribute."},
	{ID: "MB_ATT_WESTARM5", Name: "Westarm5", MaxLevel: 3, Category: "General", Description: "Westarm5 attribute."},
	{ID: "MB_ATT_DLT20A", Name: "Dlt20A", MaxLevel: 3, Category: "General", Description: "Dlt20A attribute."},
	{ID: "MB_ATT_FRAGS", Name: "Frags", MaxLevel: 3, Category: "General", Description: "Frags attribute."},
	{ID: "MB_ATT_EE3", Name: "Ee3", MaxLevel: 3, Category: "General", Description: "Ee3 attribute."},
	{ID: "MB_ATT_EE4", Name: "Ee4", MaxLevel: 3, Category: "General", Description: "Ee4 attribute."},
	{ID: "MB_ATT_AMBAN", Name: "Amban", MaxLevel: 3, Category: "General", Description: "Amban attribute."},
	{ID: "MB_ATT_BESKAR", Name: "Beskar", MaxLevel: 3, Category: "General", Description: "Beskar attribute."},
	{ID: "MB_ATT_WHISTLINGBIRD", Name: "Whistlingbird", MaxLevel: 3, Category: "General", Description: "Whistlingbird attribute."},
	{ID: "MB_ATT_CR2", Name: "Cr2", MaxLevel: 3, Category: "General", Description: "Cr2 attribute."},
	{ID: "MB_ATT_DC_CARBINE", Name: "Dc Carbine", MaxLevel: 3, Category: "General", Description: "Dc Carbine attribute."},
	{ID: "MB_ATT_E_22", Name: "E 22", MaxLevel: 3, Category: "General", Description: "E 22 attribute."},
	{ID: "MB_ATT_HEAVY_PISTOL", Name: "Heavy Pistol", MaxLevel: 3, Category: "Weapons", Description: "Heavy Pistol attribute."},
	{ID: "MB_ATT_DLT19", Name: "Dlt19", MaxLevel: 3, Category: "General", Description: "Dlt19 attribute."},
	{ID: "MB_ATT_TRAD_BOWCASTER", Name: "Trad Bowcaster", MaxLevel: 3, Category: "General", Description: "Trad Bowcaster attribute."},
	{ID: "MB_ATT_IONRIFLE", Name: "Ionrifle", MaxLevel: 3, Category: "Weapons", Description: "Ionrifle attribute."},
	{ID: "MB_ATT_REPEATER", Name: "Repeater", MaxLevel: 3, Category: "General", Description: "Repeater attribute."},
	{ID: "MB_ATT_FLECHETTE", Name: "Flechette", MaxLevel: 3, Category: "General", Description: "Flechette attribute."},
	{ID: "MB_ATT_DEMP2", Name: "Demp2", MaxLevel: 3, Category: "General", Description: "Demp2 attribute."},
	{ID: "MB_ATT_THROWER", Name: "Thrower", MaxLevel: 3, Category: "General", Description: "Thrower attribute."},
	{ID: "MB_ATT_DET_PACK", Name: "Det Pack", MaxLevel: 3, Category: "General", Description: "Det Pack attribute."},
	{ID: "MB_ATT_CONCUSSION", Name: "Concussion", MaxLevel: 3, Category: "General", Description: "Concussion attribute."},
	{ID: "MB_ATT_ROCKET_LAUNCHER", Name: "Rocket Launcher", MaxLevel: 3, Category: "Weapons", Description: "Rocket Launcher attribute."},
	{ID: "MB_ATT_BRYAR_OLD", Name: "Bryar Old", MaxLevel: 3, Category: "General", Description: "Bryar Old attribute."},
	{ID: "MB_ATT_STUN_BATON", Name: "Stun Baton", MaxLevel: 3, Category: "General", Description: "Stun Baton attribute."},
	{ID: "MB_ATT_BASE_TD", Name: "Base Td", MaxLevel: 3, Category: "General", Description: "Base Td attribute."},
	{ID: "MB_ATT_UGL", Name: "Ugl", MaxLevel: 3, Category: "General", Description: "Ugl attribute."},
	{ID: "MB_ATT_MGL", Name: "Mgl", MaxLevel: 3, Category: "General", Description: "Mgl attribute."},
	{ID: "MB_ATT_STICKY_BOMBS", Name: "Sticky Bombs", MaxLevel: 3, Category: "General", Description: "Sticky Bombs attribute."},
	{ID: "MB_ATT_MINIGUN", Name: "Minigun", MaxLevel: 3, Category: "General", Description: "Minigun attribute."},
	{ID: "MB_ATT_HULL_REPAIR", Name: "Hull Repair", MaxLevel: 3, Category: "General", Description: "Hull Repair attribute."},
	{ID: "MB_ATT_SECURITY_INTERFACE", Name: "Security Interface", MaxLevel: 3, Category: "General", Description: "Security Interface attribute."},
	{ID: "MB_ATT_DEKA_FIREPOWER", Name: "Deka Firepower", MaxLevel: 3, Category: "Class Specific", Description: "Deka Firepower attribute."},
	{ID: "MB_ATT_CLOAK", Name: "Cloak", MaxLevel: 3, Category: "General", Description: "Cloak attribute."},
	{ID: "MB_ATT_SPAWNER", Name: "Spawner", MaxLevel: 3, Category: "General", Description: "Spawner attribute."},
	{ID: "MB_ATT_STIMPACK", Name: "Stimpack", MaxLevel: 3, Category: "General", Description: "Stimpack attribute."},
	{ID: "MB_ATT_EWEB", Name: "Eweb", MaxLevel: 3, Category: "General", Description: "Eweb attribute."},
	{ID: "MB_ATT_FORCEFIELD", Name: "Forcefield", MaxLevel: 3, Category: "General", Description: "Forcefield attribute."},
	{ID: "MB_ATT_MEDI_PACK", Name: "Medi Pack", MaxLevel: 3, Category: "General", Description: "Medi Pack attribute."},
	{ID: "MB_ATT_AMMO_PACK", Name: "Ammo Pack", MaxLevel: 3, Category: "General", Description: "Ammo Pack attribute."},
	{ID: "MB_ATT_DEFLECT", Name: "Deflect", MaxLevel: 3, Category: "General", Description: "Deflect attribute."},
	{ID: "MB_ATT_FORCEBLOCK", Name: "Forceblock", MaxLevel: 3, Category: "General", Description: "Forceblock attribute."},
	{ID: "MB_ATT_FORCEFOCUS", Name: "Forcefocus", MaxLevel: 3, Category: "General", Description: "Forcefocus attribute."},
	{ID: "MB_ATT_FORCEATTUNE", Name: "Forceattune", MaxLevel: 3, Category: "General", Description: "Forceattune attribute."},
	{ID: "MB_ATT_GUN_DEFENSE", Name: "Gun Defense", MaxLevel: 3, Category: "General", Description: "Gun Defense attribute."},
	{ID: "MB_ATT_SABER_FAST", Name: "Saber Fast", MaxLevel: 3, Category: "Saber", Description: "Saber Fast attribute."},
	{ID: "MB_ATT_SABER_MEDIUM", Name: "Saber Medium", MaxLevel: 3, Category: "Saber", Description: "Saber Medium attribute."},
	{ID: "MB_ATT_SABER_STRONG", Name: "Saber Strong", MaxLevel: 3, Category: "Saber", Description: "Saber Strong attribute."},
	{ID: "MB_ATT_SABER_DOUBLES", Name: "Saber Doubles", MaxLevel: 3, Category: "Saber", Description: "Saber Doubles attribute."},
	{ID: "MB_ATT_SABER_MASTERY", Name: "Saber Mastery", MaxLevel: 3, Category: "Saber", Description: "Saber Mastery attribute."},
	{ID: "MB_ATT_SABER_COMBO", Name: "Saber Combo", MaxLevel: 3, Category: "Saber", Description: "Saber Combo attribute."},
	{ID: "MB_ATT_SABER_COMBO_NONE", Name: "Saber Combo None", MaxLevel: 3, Category: "Saber", Description: "Saber Combo None attribute."},
	{ID: "MB_ATT_SS_YELLOWSTYLE", Name: "Ss Yellowstyle", MaxLevel: 3, Category: "General", Description: "Ss Yellowstyle attribute."},
	{ID: "MB_ATT_SS_BLUESTYLE", Name: "Ss Bluestyle", MaxLevel: 3, Category: "General", Description: "Ss Bluestyle attribute."},
	{ID: "MB_ATT_SS_REDSTYLE", Name: "Ss Redstyle", MaxLevel: 3, Category: "General", Description: "Ss Redstyle attribute."},
	{ID: "MB_ATT_SS_PURPLESTYLE", Name: "Ss Purplestyle", MaxLevel: 3, Category: "General", Description: "Ss Purplestyle attribute."},
	{ID: "MB_ATT_SS_CYANSTYLE", Name: "Ss Cyanstyle", MaxLevel: 3, Category: "General", Description: "Ss Cyanstyle attribute."},
	{ID: "MB_ATT_SS_GREENSTYLE", Name: "Ss Greenstyle", MaxLevel: 3, Category: "General", Description: "Ss Greenstyle attribute."},
	{ID: "MB_ATT_SS_DUALSTYLE", Name: "Ss Dualstyle", MaxLevel: 3, Category: "General", Description: "Ss Dualstyle attribute."},
	{ID: "MB_ATT_SS_STAFFSTYLE", Name: "Ss Staffstyle", MaxLevel: 3, Category: "General", Description: "Ss Staffstyle attribute."},
	{ID: "MB_ATT_FP_MIRALUKA", Name: "Force Miraluka", MaxLevel: 3, Category: "Force", Description: "Force Miraluka attribute."},
	{ID: "MB_ATT_GUNBASH", Name: "Gunbash", MaxLevel: 3, Category: "General", Description: "Gunbash attribute."},
	{ID: "MB_ATT_ROSHTAUNT", Name: "Roshtaunt", MaxLevel: 3, Category: "General", Description: "Roshtaunt attribute."},
	{ID: "MB_ATT_FP_REPULSE", Name: "Force Repulse", MaxLevel: 3, Category: "Force", Description: "Force Repulse attribute."},
	{ID: "MB_ATT_FLIPKICK", Name: "Flipkick", MaxLevel: 3, Category: "General", Description: "Flipkick attribute."},
	{ID: "MB_ATT_LIGHTS_BEACON", Name: "Lights Beacon", MaxLevel: 3, Category: "General", Description: "Lights Beacon attribute."},
	{ID: "MB_ATT_TRIP_MINES", Name: "Trip Mines", MaxLevel: 3, Category: "General", Description: "Trip Mines attribute."},
	{ID: "MB_ATT_MANUALSABERTHROW", Name: "Manualsaberthrow", MaxLevel: 3, Category: "Saber", Description: "Manualsaberthrow attribute."},
	{ID: "MB_ATT_ASTRO_JUMPJETS", Name: "Astro Jumpjets", MaxLevel: 3, Category: "General", Description: "Astro Jumpjets attribute."},
	{ID: "MB_ATT_HEAT_DUMPS", Name: "Heat Dumps", MaxLevel: 3, Category: "General", Description: "Heat Dumps attribute."},
	{ID: "MB_ATT_WELDING_LASER", Name: "Welding Laser", MaxLevel: 3, Category: "General", Description: "Welding Laser attribute."},
	{ID: "MB_ATT_SHOCK_ARM", Name: "Shock Arm", MaxLevel: 3, Category: "General", Description: "Shock Arm attribute."},
	{ID: "MB_ATT_FIRE_EXTINGUISHER", Name: "Fire Extinguisher", MaxLevel: 3, Category: "General", Description: "Fire Extinguisher attribute."},
	{ID: "MB_ATT_DATA_SPIKES", Name: "Data Spikes", MaxLevel: 3, Category: "General", Description: "Data Spikes attribute."},
	{ID: "MB_ATT_WATER_BREATHING", Name: "Water Breathing", MaxLevel: 3, Category: "General", Description: "Water Breathing attribute."},
	{ID: "MB_ATT_SBD_BATTERY", Name: "Sbd Battery", MaxLevel: 3, Category: "Class Specific", Description: "Sbd Battery attribute."},
	{ID: "MB_ATT_SBD_MODE_ARMOR", Name: "Sbd Mode Armor", MaxLevel: 3, Category: "Class Specific", Description: "Sbd Mode Armor attribute."},
	{ID: "MB_ATT_SBD_MODE_SPEED", Name: "Sbd Mode Speed", MaxLevel: 3, Category: "Class Specific", Description: "Sbd Mode Speed attribute."},
	{ID: "MB_ATT_SBD_MODE_FIREPOWER", Name: "Sbd Mode Firepower", MaxLevel: 3, Category: "Class Specific", Description: "Sbd Mode Firepower attribute."},
	{ID: "MB_ATT_SBD_MODE_STRENGTH", Name: "Sbd Mode Strength", MaxLevel: 3, Category: "Class Specific", Description: "Sbd Mode Strength attribute."},
	{ID: "MB_ATT_SBD_WRISTROCKET", Name: "Sbd Wristrocket", MaxLevel: 3, Category: "Weapons", Description: "Sbd Wristrocket attribute."},
	{ID: "MB_ATT_SBD_DUALBLASTERS", Name: "Sbd Dualblasters", MaxLevel: 3, Category: "Weapons", Description: "Sbd Dualblasters attribute."},
	{ID: "MB_ATT_WRIST_AMMO", Name: "Wrist Ammo", MaxLevel: 3, Category: "General", Description: "Wrist Ammo attribute."},
	{ID: "MB_ATT_INAIR_FORCE_REGEN", Name: "Inair Force Regen", MaxLevel: 3, Category: "General", Description: "Inair Force Regen attribute."},
	{ID: "MB_ATT_BUNNY_HOP", Name: "Bunny Hop", MaxLevel: 3, Category: "General", Description: "Bunny Hop attribute."},
	{ID: "MB_ATT_FLOAT_HOP", Name: "Float Hop", MaxLevel: 3, Category: "General", Description: "Float Hop attribute."},
	{ID: "MB_ATT_GRAPPLE_HOP", Name: "Grapple Hop", MaxLevel: 3, Category: "General", Description: "Grapple Hop attribute."},
	{ID: "MB_ATT_TRACKING_BEACON", Name: "Tracking Beacon", MaxLevel: 3, Category: "General", Description: "Tracking Beacon attribute."},
	{ID: "MB_ATT_SUPPLYDROP", Name: "Supplydrop", MaxLevel: 3, Category: "General", Description: "Supplydrop attribute."},
	{ID: "MB_ATT_USE_DISTANCE", Name: "Use Distance", MaxLevel: 3, Category: "General", Description: "Use Distance attribute."},
	{ID: "MB_ATT_DISP_HEALTH", Name: "Disp Health", MaxLevel: 3, Category: "General", Description: "Disp Health attribute."},
	{ID: "MB_ATT_DISP_AMMO", Name: "Disp Ammo", MaxLevel: 3, Category: "General", Description: "Disp Ammo attribute."},
	{ID: "MB_ATT_DISP_ARMOR", Name: "Disp Armor", MaxLevel: 3, Category: "General", Description: "Disp Armor attribute."},
	{ID: "MB_ATT_DISP_FORCE", Name: "Disp Force", MaxLevel: 3, Category: "General", Description: "Disp Force attribute."},
	{ID: "MB_ATT_DISP_BLOCK", Name: "Disp Block", MaxLevel: 3, Category: "General", Description: "Disp Block attribute."},
	{ID: "MB_ATT_DROP_HEALTH", Name: "Drop Health", MaxLevel: 3, Category: "General", Description: "Drop Health attribute."},
	{ID: "MB_ATT_DROP_AMMO", Name: "Drop Ammo", MaxLevel: 3, Category: "General", Description: "Drop Ammo attribute."},
	{ID: "MB_ATT_DROP_ARMOR", Name: "Drop Armor", MaxLevel: 3, Category: "General", Description: "Drop Armor attribute."},
	{ID: "MB_ATT_DROP_FORCE", Name: "Drop Force", MaxLevel: 3, Category: "General", Description: "Drop Force attribute."},
	{ID: "MB_ATT_DROP_BLOCK", Name: "Drop Block", MaxLevel: 3, Category: "General", Description: "Drop Block attribute."},
	{ID: "MB_ATT_STIM_HEALTH", Name: "Stim Health", MaxLevel: 3, Category: "General", Description: "Stim Health attribute."},
	{ID: "MB_ATT_STIM_AMMO", Name: "Stim Ammo", MaxLevel: 3, Category: "General", Description: "Stim Ammo attribute."},
	{ID: "MB_ATT_STIM_ARMOR", Name: "Stim Armor", MaxLevel: 3, Category: "General", Description: "Stim Armor attribute."},
	{ID: "MB_ATT_STIM_FORCE", Name: "Stim Force", MaxLevel: 3, Category: "General", Description: "Stim Force attribute."},
	{ID: "MB_ATT_STIM_BLOCK", Name: "Stim Block", MaxLevel: 3, Category: "General", Description: "Stim Block attribute."},
	{ID: "MB_ATT_THROWER_LIGHTNING", Name: "Thrower Lightning", MaxLevel: 3, Category: "General", Description: "Thrower Lightning attribute."},
	{ID: "MB_ATT_THROWER_ICE", Name: "Thrower Ice", MaxLevel: 3, Category: "General", Description: "Thrower Ice attribute."},
	{ID: "MB_ATT_THROWER_PLASMA", Name: "Thrower Plasma", MaxLevel: 3, Category: "General", Description: "Thrower Plasma attribute."},
	{ID: "MB_ATT_THROWER_FLAME", Name: "Thrower Flame", MaxLevel: 3, Category: "General", Description: "Thrower Flame attribute."},
	{ID: "MB_ATT_REMOTE_DETONATE", Name: "Remote Detonate", MaxLevel: 3, Category: "General", Description: "Remote Detonate attribute."},
	{ID: "MB_ATT_GETUPS", Name: "Getups", MaxLevel: 3, Category: "General", Description: "Getups attribute."},
	{ID: "MB_ATT_FP_FINAL", Name: "Force Final", MaxLevel: 3, Category: "Force", Description: "Force Final attribute."},
	{ID: "MB_ATT_PISTOL", Name: "Pistol", MaxLevel: 3, Category: "Weapons", Description: "Pistol attribute."},
}
