package main

// Cross-platform update-installer glue.
//
// InstallUpdate is the single entry point called by the Home-screen
// banner. The platform-specific heavy lifting lives in
// update_installer_{darwin,linux,windows}.go — this file just holds
// the shared download helper, the Ed25519 manifest verification, and
// the small error type the UI uses to decide whether to show a toast
// vs. open the release page.
//
// Trust reality: a passing InstallUpdate proves the artifact matches
// the manifest signed by the publisher's Ed25519 key (PublisherTrustedKey,
// embedded at build time). It says nothing about Apple Developer ID,
// notarization, or any OS trust store. When PublisherTrustedKey is
// absent or the signature does not verify, auto-install fails closed.

import (
	"bytes"
	"crypto/ed25519"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"github.com/Frenzeh/mbii-foundry/updatemanifest"
	"golang.org/x/text/cases"
	"golang.org/x/text/unicode/norm"

	"fyne.io/fyne/v2"
)

// ErrUpdateNotSupported is returned by platforms where the auto-
// installer can't run (e.g. Windows, where SmartScreen blocks
// swapping unsigned binaries). The UI falls back to opening the
// release page in the user's browser.
var ErrUpdateNotSupported = errors.New("auto-update not supported on this platform")

// UpdateProgress is passed to InstallUpdate's progress callback so
// the banner can render a "Downloading… 34%" state without the
// caller having to marshal bytes themselves.
type UpdateProgress struct {
	Stage   string  // "downloading", "extracting", "installing", "relaunching"
	Percent float64 // 0-100, negative if unknown
	Message string  // human-readable status
}

// PublisherTrustedKey is the configured hex-encoded Ed25519 public key.
// Must be set via build tags or configuration for the installer to proceed.
var PublisherTrustedKey string

// UpdateManifest mirrors the manifest generated by the signer tool.
type UpdateManifest struct {
	Version      string `json:"version"`
	Platform     string `json:"platform"`
	Architecture string `json:"architecture"`
	Length       int64  `json:"length"`
	Digest       string `json:"digest"`
	Signature    string `json:"signature"`
}

// InstallUpdate downloads and installs the release asset for this
// platform. On success it exits the process (after relaunching the
// new binary) so the caller should treat a nil return as "process
// is about to die, don't touch the UI."
//
// progress is optional; pass nil to skip progress reporting.
func InstallUpdate(info *UpdateInfo, progress func(UpdateProgress)) error {
	if info == nil {
		return errors.New("no update info provided")
	}
	asset := AssetForPlatform(info)
	if asset == nil {
		return errors.New("no release asset for this platform")
	}
	if PublisherTrustedKey == "" {
		return errors.New("auto-install disabled: no trusted publisher key configured")
	}

	manifest, err := fetchUpdateManifest(
		&http.Client{Timeout: 30 * time.Second},
		asset.BrowserDownloadURL+".manifest.json",
	)
	if err != nil {
		return err
	}
	if manifest.Version != info.TagName {
		return fmt.Errorf("manifest version mismatch: got %s, expected requested release %s", manifest.Version, info.TagName)
	}
	if manifest.Platform != runtime.GOOS {
		return fmt.Errorf("manifest platform mismatch: got %s, expected %s", manifest.Platform, runtime.GOOS)
	}
	expectedArch := runtime.GOARCH
	if runtime.GOOS == "darwin" {
		expectedArch = "universal"
	}
	if manifest.Architecture != expectedArch {
		return fmt.Errorf("manifest architecture mismatch: got %s, expected %s", manifest.Architecture, expectedArch)
	}
	if manifest.Length < 0 || manifest.Length > updatemanifest.MaxArtifactBytes {
		return fmt.Errorf("manifest length out of range: %d", manifest.Length)
	}
	if err := updatemanifest.ValidateDigest(manifest.Digest); err != nil {
		return fmt.Errorf("malformed manifest: %w", err)
	}

	pubBytes, err := decodeCanonicalHex(PublisherTrustedKey, ed25519.PublicKeySize, "publisher public key")
	if err != nil {
		return fmt.Errorf("invalid publisher public key configuration: %w", err)
	}
	sigBytes, err := decodeCanonicalHex(manifest.Signature, ed25519.SignatureSize, "manifest signature")
	if err != nil {
		return err
	}
	payload, err := updatemanifest.Payload(
		manifest.Version,
		manifest.Platform,
		manifest.Architecture,
		manifest.Length,
		manifest.Digest,
	)
	if err != nil {
		return fmt.Errorf("malformed manifest: %w", err)
	}
	if !ed25519.Verify(ed25519.PublicKey(pubBytes), payload, sigBytes) {
		return errors.New("manifest signature verification failed: untrusted update")
	}

	return installUpdatePlatform(asset, manifest, progress)
}

const maxManifestBytes = 16 * 1024

func fetchUpdateManifest(client *http.Client, manifestURL string) (UpdateManifest, error) {
	req, err := http.NewRequest(http.MethodGet, manifestURL, nil)
	if err != nil {
		return UpdateManifest{}, fmt.Errorf("create manifest request: %w", err)
	}
	req.Header.Set("User-Agent", "mbii-foundry-updater/1.0")

	resp, err := client.Do(req)
	if err != nil {
		return UpdateManifest{}, fmt.Errorf("fetch manifest: %w", err)
	}
	body, readErr := io.ReadAll(io.LimitReader(resp.Body, maxManifestBytes+1))
	closeErr := resp.Body.Close()
	if readErr != nil {
		return UpdateManifest{}, fmt.Errorf("read manifest: %w", readErr)
	}
	if closeErr != nil {
		return UpdateManifest{}, fmt.Errorf("close manifest response: %w", closeErr)
	}
	if resp.StatusCode != http.StatusOK {
		return UpdateManifest{}, fmt.Errorf("manifest download failed: HTTP %s", resp.Status)
	}
	if len(body) > maxManifestBytes {
		return UpdateManifest{}, fmt.Errorf("manifest exceeds %d-byte limit", maxManifestBytes)
	}
	if len(bytes.TrimSpace(body)) == 0 {
		return UpdateManifest{}, errors.New("parse manifest: empty response")
	}

	decoder := json.NewDecoder(bytes.NewReader(body))
	decoder.DisallowUnknownFields()
	var manifest UpdateManifest
	if err := decoder.Decode(&manifest); err != nil {
		return UpdateManifest{}, fmt.Errorf("parse manifest: %w", err)
	}
	var trailing any
	if err := decoder.Decode(&trailing); !errors.Is(err, io.EOF) {
		if err == nil {
			return UpdateManifest{}, errors.New("parse manifest: trailing JSON value")
		}
		return UpdateManifest{}, fmt.Errorf("parse manifest trailing data: %w", err)
	}
	return manifest, nil
}

func decodeCanonicalHex(encoded string, byteLength int, field string) ([]byte, error) {
	if len(encoded) != byteLength*2 {
		return nil, fmt.Errorf("%s has invalid length: got %d hex characters, want %d", field, len(encoded), byteLength*2)
	}
	decoded, err := hex.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("%s is not valid hex: %w", field, err)
	}
	if hex.EncodeToString(decoded) != encoded {
		return nil, fmt.Errorf("%s is not canonical lowercase hex", field)
	}
	return decoded, nil
}

// downloadToTemp fetches the asset into a temp directory and returns
// the local file path + a cleanup func the caller should defer.
func downloadToTemp(asset *ReleaseAsset, manifest UpdateManifest, progress func(UpdateProgress)) (string, func(), error) {
	return downloadToTempWithClient(&http.Client{Timeout: 5 * time.Minute}, asset, manifest, progress)
}

func downloadToTempWithClient(client *http.Client, asset *ReleaseAsset, manifest UpdateManifest, progress func(UpdateProgress)) (string, func(), error) {
	if manifest.Length < 0 || manifest.Length > updatemanifest.MaxArtifactBytes {
		return "", nil, fmt.Errorf("manifest length out of range: %d", manifest.Length)
	}
	expectedDigest, err := decodeCanonicalHex(manifest.Digest, sha256.Size, "manifest digest")
	if err != nil {
		return "", nil, err
	}
	if asset.Name == "" || asset.Name == "." || asset.Name == ".." ||
		filepath.Base(asset.Name) != asset.Name || strings.ContainsAny(asset.Name, `/\`) {
		return "", nil, fmt.Errorf("invalid asset name: %s", asset.Name)
	}
	for _, r := range asset.Name {
		if r < 0x20 || r == 0x7f {
			return "", nil, fmt.Errorf("invalid asset name: %q", asset.Name)
		}
	}

	tmpDir, err := os.MkdirTemp("", "foundry-update-*")
	if err != nil {
		return "", nil, fmt.Errorf("create temp dir: %w", err)
	}
	cleanup := func() { _ = os.RemoveAll(tmpDir) }

	req, err := http.NewRequest(http.MethodGet, asset.BrowserDownloadURL, nil)
	if err != nil {
		cleanup()
		return "", nil, fmt.Errorf("create download request: %w", err)
	}
	req.Header.Set("User-Agent", "mbii-foundry-updater/1.0")
	req.Header.Set("Accept", "application/octet-stream")

	resp, err := client.Do(req)
	if err != nil {
		cleanup()
		return "", nil, fmt.Errorf("download %s: %w", asset.Name, err)
	}
	if resp.StatusCode != http.StatusOK {
		closeErr := resp.Body.Close()
		cleanup()
		statusErr := fmt.Errorf("download %s: server returned %s", asset.Name, resp.Status)
		if closeErr != nil {
			return "", nil, errors.Join(statusErr, fmt.Errorf("close download response: %w", closeErr))
		}
		return "", nil, statusErr
	}

	localPath := filepath.Join(tmpDir, asset.Name)
	out, err := os.OpenFile(localPath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0600)
	if err != nil {
		closeErr := resp.Body.Close()
		cleanup()
		return "", nil, errors.Join(
			fmt.Errorf("create %s: %w", localPath, err),
			wrapError("close download response", closeErr),
		)
	}

	hasher := sha256.New()
	limitReader := io.LimitReader(resp.Body, manifest.Length+1)
	r := &progressReader{
		r:     limitReader,
		total: manifest.Length,
		cb: func(read int64) {
			if progress == nil || manifest.Length <= 0 {
				return
			}
			progress(UpdateProgress{
				Stage:   "downloading",
				Percent: 100 * float64(read) / float64(manifest.Length),
				Message: fmt.Sprintf("Downloading %s…", asset.Name),
			})
		},
	}

	copied, copyErr := io.Copy(io.MultiWriter(out, hasher), r)
	syncErr := out.Sync()
	fileCloseErr := out.Close()
	bodyCloseErr := resp.Body.Close()
	if copyErr != nil || syncErr != nil || fileCloseErr != nil || bodyCloseErr != nil {
		cleanup()
		return "", nil, errors.Join(
			wrapError("save "+asset.Name, copyErr),
			wrapError("sync "+asset.Name, syncErr),
			wrapError("close "+asset.Name, fileCloseErr),
			wrapError("close download response", bodyCloseErr),
		)
	}
	if copied != manifest.Length {
		cleanup()
		return "", nil, fmt.Errorf("downloaded length %d does not match manifest length %d", copied, manifest.Length)
	}
	if subtle.ConstantTimeCompare(hasher.Sum(nil), expectedDigest) != 1 {
		cleanup()
		return "", nil, errors.New("downloaded digest does not match manifest digest")
	}

	return localPath, cleanup, nil
}

func wrapError(operation string, err error) error {
	if err == nil {
		return nil
	}
	return fmt.Errorf("%s: %w", operation, err)
}

// progressReader wraps an io.Reader with a byte-count callback.
// Throttled to one callback per ~256KB so the UI isn't hammered.
type progressReader struct {
	r     io.Reader
	total int64
	read  int64
	last  int64
	cb    func(int64)
}

func (p *progressReader) Read(b []byte) (int, error) {
	n, err := p.r.Read(b)
	p.read += int64(n)
	if p.cb != nil && (p.read-p.last > 256<<10 || err == io.EOF) {
		p.last = p.read
		p.cb(p.read)
	}
	return n, err
}

// relaunchAndExit starts a fresh instance of the given binary and
// exits the current one. Used by the platform installers after the
// on-disk swap completes.
//
// We give the new process ~1 second of head start before fyne.Do-ing
// the exit so the window manager handoff is smooth — calling
// os.Exit immediately has, on both Mac and Linux, occasionally left
// the new process fighting for focus against a disappearing ghost.
func relaunchAndExit(binaryPath string, args ...string) error {
	cmd := exec.Command(binaryPath, args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Start(); err != nil {
		return fmt.Errorf("relaunch %s: %w", binaryPath, err)
	}
	// Detach so we don't block if the parent lingers.
	go func() { _ = cmd.Process.Release() }()

	go func() {
		time.Sleep(700 * time.Millisecond)
		fyne.Do(func() {
			LogInfo("Relaunching into %s", binaryPath)
			os.Exit(0)
		})
	}()
	return nil
}

// archiveEntryKey maps an archive member name onto its collision
// identity for duplicate detection: Unicode NFC normalization plus
// case folding. On case-insensitive filesystems (macOS APFS default,
// some SMB/NFS mounts) two entries that differ only by case or by
// canonical form (e.g. "Café" spelled NFC vs NFD) would extract onto
// the same path, so extractors reject them as aliases at
// prevalidation time. This is a collision detector for archive
// members, not a general-purpose Unicode security fold.
var archiveCaseFolder = cases.Fold()

func archiveEntryKey(name string) string {
	name = strings.TrimSuffix(name, "/")
	return norm.NFC.String(archiveCaseFolder.String(norm.NFC.String(name)))
}

// appBundleContainingExe walks up from the current executable path
// looking for the enclosing ".app" bundle, if any. Returns "" when
// the binary isn't inside a bundle (dev-mode / raw binary on Linux).
// Used by the Mac installer to decide between bundle-swap and raw-
// binary swap.
func appBundleContainingExe() string {
	if runtime.GOOS != "darwin" {
		return ""
	}
	exe, err := os.Executable()
	if err != nil {
		return ""
	}
	dir := filepath.Dir(exe)
	for i := 0; i < 8 && dir != "/" && dir != "."; i++ {
		if filepath.Ext(dir) == ".app" {
			return dir
		}
		dir = filepath.Dir(dir)
	}
	return ""
}
